site_name: Paleofuturistic Python
site_author: Carlo 'carlovo' van Overbeek
site_description: The Python development workflow your past self had always hoped for is finally here!

repo_url: https://github.com/schubergphilis/paleofuturistic_python
edit_uri: blob/main/docs/

theme:
  name: mkdocs
  color_mode: auto
  user_color_mode_toggle: true
  locale: en

nav:
  - Home: index.md
  - Walkthrough: walkthrough.md
  - About: about.md

copyright: Copyright &copy; 2024 <a href="https://schubergphilis.com/">Schuberg Philis</a>
